### ISSUE TITLE
New repository and still empty. Please stop being a sinner.

### ISSUE THREAD

**Issue by cipisek8** [matakom/bible-memorization#1]
Would you please stop? Why are you doing this? You made a new repository just to make my **rightfull** accusations disappear, and yet you leave the new one empty? Do you reallly not care about our _lord and saviour_? Do you **_WANT_** to go to hell?????

**Comment by matakom** [comment]
I see your point, but maybe take a moment to read Ecclesiastes 3:1-8 before jumping to conclusions. There’s a time to code and a time to wait, a time to commit and a time to... not commit. The repo’s time will come—patience is key, my friend.
